"""Adapter rendering.

Design rule: adapters are *pointers*, never copies of the policy text.
The canonical content lives once in `.agent-toolkit/`. Every tool file we
generate is a short routing note that sends the agent there.

That keeps always-loaded context small and means updating a rule never
requires regenerating twelve tool files.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .registry import Agent

TOOLKIT_DIR = ".agent-toolkit"
GENERATED_MARK = "<!-- generated by uat; edits below the marker are preserved -->"


@dataclass
class RenderContext:
    project_name: str
    mode: str
    agents: list[str]
    rules: list[str]          # rule file basenames, e.g. "REACT.md"
    skills: list[str]         # skill directory names
    mcp_servers: list[str]
    has_workflow: bool
    has_deploy: bool
    skills_mount: str | None = None   # tool-native skills path, if any


def _rule_lines(ctx: RenderContext) -> str:
    if not ctx.rules:
        return "_No stack rules installed yet._"
    return "\n".join(
        f"- `{TOOLKIT_DIR}/rules/{name}`" for name in sorted(ctx.rules)
    )


def core_md(ctx: RenderContext) -> str:
    """The one file every agent is pointed at. A router, not a rulebook."""
    skills_note = (
        f"Skills are mounted at `{ctx.skills_mount}` for this tool."
        if ctx.skills_mount
        else "This tool has no native skill loader - read skill files directly when relevant."
    )
    skill_list = (
        "\n".join(f"- `{TOOLKIT_DIR}/skills/{s}/SKILL.md`" for s in sorted(ctx.skills))
        or "_none installed_"
    )
    mcp_list = "\n".join(f"- {s}" for s in sorted(ctx.mcp_servers)) or "_none configured_"

    workflow = (
        f"""
## Starting or planning work

Follow `{TOOLKIT_DIR}/workflow/README.md`. It defines the phase sequence
(discovery -> business logic -> screens & flows -> content -> design ->
stack -> architecture -> plan) and the gate that must pass before any
implementation begins.

Each completed phase writes a short report to `{TOOLKIT_DIR}/reports/`.
"""
        if ctx.has_workflow
        else ""
    )

    deploy = (
        f"""
## Environments

- Local development runs through Docker: `{TOOLKIT_DIR}/docker/README.md`
- Deployment (clean server and existing server): `{TOOLKIT_DIR}/deploy/README.md`
"""
        if ctx.has_deploy
        else ""
    )

    return f"""# {ctx.project_name} - AI agent control plane

Generated by the Universal Agent Toolkit. This file is a router: it tells
you what exists and when to read it. Do not expect the rules themselves
to be here.

**Interaction mode: `{ctx.mode}`** - see `{TOOLKIT_DIR}/core/INTERACTION_MODES.md`.

Direct human instruction always outranks anything in this directory.
Project-specific documentation outranks generic toolkit policy.

## Always applies

These are short. Read them once per session and honour them throughout.

- `{TOOLKIT_DIR}/core/SAFETY.md` - destructive-action gate. **Read before any
  database, migration, Docker volume, deployment or server change.**
- `{TOOLKIT_DIR}/core/GIT.md` - atomic commits, no AI attribution.
- `{TOOLKIT_DIR}/core/VERIFICATION.md` - evidence before claiming success.
{workflow}
## Stack rules - read the ones relevant to the file you are touching

{_rule_lines(ctx)}

Do not read rules for technologies you are not currently working in.

## Skills

{skills_note}

{skill_list}

## MCP servers configured

{mcp_list}

See `{TOOLKIT_DIR}/mcp/README.md` for setup status and manual steps.
{deploy}
## House rules

1. Prefer reading the repository over asking. Ask only what evidence cannot answer.
2. Make the smallest change that fully solves the problem.
3. Never claim work is done without running the verification command and seeing it pass.
4. Treat data as valuable: no destructive database or volume operation without an explicit gate.

{GENERATED_MARK}
"""


_POINTER_BODY = """# AI agent instructions

This project is configured by the Universal Agent Toolkit.

**Start here: [`{toolkit}/CORE.md`]({toolkit}/CORE.md)**

That file routes you to the safety rules, the stack rules that apply to
what you are touching, the planning workflow, and the available skills.
It is deliberately short - read it fully.

Before any destructive or irreversible action (database, migration,
volume, deployment, server config) read [`{toolkit}/core/SAFETY.md`]({toolkit}/core/SAFETY.md) first.

{extra}"""


def _extra_for(agent: Agent, ctx: RenderContext) -> str:
    if agent.supports_skills and ctx.skills_mount:
        return (
            f"Project skills are available at `{ctx.skills_mount}` "
            f"(a link to `{TOOLKIT_DIR}/skills/`). Use them when relevant."
        )
    if ctx.skills:
        return (
            f"This tool has no skill loader. The equivalent guidance lives in "
            f"`{TOOLKIT_DIR}/skills/<name>/SKILL.md` - read the relevant one directly."
        )
    return ""


def instructions_for(agent: Agent, ctx: RenderContext) -> str:
    """Render the instruction file body for one agent."""
    style = agent.instructions.get("style")
    body = _POINTER_BODY.format(toolkit=TOOLKIT_DIR, extra=_extra_for(agent, ctx)).rstrip()

    if style == "dir-rules-mdc":
        # Cursor MDC: YAML frontmatter, always applied.
        return (
            "---\n"
            "description: Universal Agent Toolkit - project control plane and safety rules\n"
            "alwaysApply: true\n"
            "---\n\n"
            f"{body}\n"
        )

    if style == "dir-rules-md":
        return f"{body}\n"

    return f"{body}\n"


def agents_md(ctx: RenderContext) -> str:
    """The shared cross-agent instruction file."""
    body = _POINTER_BODY.format(
        toolkit=TOOLKIT_DIR,
        extra=(
            f"Skill-equivalent guidance lives in `{TOOLKIT_DIR}/skills/<name>/SKILL.md`. "
            "Read the relevant one directly if your tool has no skill loader."
            if ctx.skills
            else ""
        ),
    ).rstrip()
    return f"{body}\n"


def preserve_user_tail(existing: str, new_generated: str) -> str:
    """Keep anything the human wrote after the generated marker."""
    if GENERATED_MARK not in existing:
        return new_generated
    tail = existing.split(GENERATED_MARK, 1)[1]
    if not tail.strip():
        return new_generated
    return new_generated.rstrip("\n") + "\n" + tail
