"""Adapter rendering.

Design rule: adapters are *pointers*, never copies of the policy text.
The canonical content lives once in `.agent-toolkit/`. Every tool file we
generate is a short routing note that sends the agent there.

That keeps always-loaded context small and means updating a rule never
requires regenerating twelve tool files.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from .registry import Agent

TOOLKIT_DIR = ".agent-toolkit"
GENERATED_MARK = "<!-- generated by uat; edits below the marker are preserved -->"


@dataclass
class RenderContext:
    project_name: str
    mode: str
    agents: list[str]
    rules: list[str]          # rule file basenames, e.g. "REACT.md"
    skills: list[str]         # skill directory names
    mcp_servers: list[str]
    has_workflow: bool
    has_deploy: bool
    skills_mount: str | None = None   # tool-native skills path, if any
    uat_cmd: str = "uat"              # how to invoke the CLI from this project
    always_rules: list[str] = field(default_factory=list)  # apply to all code


def uat_invocation(project, toolkit_root) -> str:
    """The exact command that runs the CLI for THIS project.

    An embedded copy is preferred, because it keeps working if the factory
    checkout moves or disappears.
    """
    embedded = project / TOOLKIT_DIR / "toolkit" / "uat"
    if embedded.is_file():
        return f"./{TOOLKIT_DIR}/toolkit/uat"
    # Deliberately NOT the absolute path of this checkout: these strings are
    # written into files that get committed and shared, where a path from one
    # developer's machine is worse than useless. Plain `uat` is portable, and
    # START-HERE.md explains where it comes from.
    return "uat"


def _rule_lines(ctx: RenderContext) -> str:
    """Only the stack-specific rules; the always-on ones are listed separately."""
    stack = [r for r in ctx.rules if r not in set(ctx.always_rules)]
    if not stack:
        return "_No stack rules installed yet._"
    return "\n".join(
        f"- `{TOOLKIT_DIR}/rules/{name}`" for name in sorted(stack)
    )


def _always_rule_lines(ctx: RenderContext) -> str:
    present = [r for r in ctx.always_rules if r in set(ctx.rules)]
    if not present:
        return ""
    lines = "\n".join(
        f"- `{TOOLKIT_DIR}/rules/{name}`" for name in sorted(present)
    )
    return (
        "\n## Code quality - applies to every file you write\n\n"
        + lines
        + "\n\nThese are not stack rules. They apply whatever the language.\n"
    )


def core_md(ctx: RenderContext) -> str:
    """The one file every agent is pointed at. A router, not a rulebook."""
    skills_note = (
        f"Skills are mounted at `{ctx.skills_mount}` for this tool."
        if ctx.skills_mount
        else "This tool has no native skill loader - read skill files directly when relevant."
    )
    skill_list = (
        "\n".join(f"- `{TOOLKIT_DIR}/skills/{s}/SKILL.md`" for s in sorted(ctx.skills))
        or "_none installed_"
    )
    mcp_list = "\n".join(f"- {s}" for s in sorted(ctx.mcp_servers)) or "_none configured_"

    workflow = (
        f"""
## Starting or planning work

**Entry point: `{TOOLKIT_DIR}/workflow/README.md`.** Read it before doing
anything on a new project, a new feature, or an unfamiliar codebase.

The sequence: triage -> discovery -> business logic -> screens & flows ->
content -> design -> stack -> rules -> architecture -> environments -> plan
-> gate. Triage decides how much of it applies; a one-line fix runs discovery
and stops.

**Nothing is implemented until the gate in `workflow/11-gate.md` passes and a
human approves.**

Each completed phase writes a short report to `{TOOLKIT_DIR}/reports/`. Read
those first when resuming - they are the decision log.

Check progress at any time:

```bash
{ctx.uat_cmd} workflow --project .
```

## Managing this install

Rules are installed per technology. When phase 06 settles the stack, phase 07
installs the matching rules - do not hand-write what a pack already provides:

```bash
{ctx.uat_cmd} detect  --project .                       # what stack is here
{ctx.uat_cmd} catalog                                   # what packs exist
{ctx.uat_cmd} install --project . --agent {ctx.agents[0] if ctx.agents else 'claude-code'} --add <pack>
{ctx.uat_cmd} status  --project .                       # installed + local drift
```

Installing is additive and idempotent; existing files are never overwritten
without `--force`.
"""
        if ctx.has_workflow
        else ""
    )

    deploy = (
        f"""
## Environments

- Local development runs through Docker: `{TOOLKIT_DIR}/docker/README.md`
- Deployment (clean server and existing server): `{TOOLKIT_DIR}/deploy/README.md`
"""
        if ctx.has_deploy
        else ""
    )

    return f"""# {ctx.project_name} - AI agent control plane

Generated by the Universal Agent Toolkit. This file is a router: it tells
you what exists and when to read it. Do not expect the rules themselves
to be here.

**Interaction mode: `{ctx.mode}`** - see `{TOOLKIT_DIR}/core/INTERACTION_MODES.md`.

Direct human instruction always outranks anything in this directory.
Project-specific documentation outranks generic toolkit policy.

## Always applies

These are short. Read them once per session and honour them throughout.

- `{TOOLKIT_DIR}/core/SAFETY.md` - destructive-action gate. **Read before any
  database, migration, Docker volume, deployment or server change.**
- `{TOOLKIT_DIR}/core/GIT.md` - atomic commits, no AI attribution.
- `{TOOLKIT_DIR}/core/VERIFICATION.md` - evidence before claiming success.
{workflow}
{_always_rule_lines(ctx)}
## Stack rules - read the ones relevant to the file you are touching

{_rule_lines(ctx)}

Do not read rules for technologies you are not currently working in.

## Skills

{skills_note}

{skill_list}

## MCP servers configured

{mcp_list}

See `{TOOLKIT_DIR}/mcp/README.md` for setup status and manual steps.
{deploy}
## House rules

1. Prefer reading the repository over asking. Ask only what evidence cannot answer.
2. Make the smallest change that fully solves the problem.
3. Never claim work is done without running the verification command and seeing it pass.
4. Treat data as valuable: no destructive database or volume operation without an explicit gate.

{GENERATED_MARK}
"""


_POINTER_BODY = """# AI agent instructions

This project is configured by the Universal Agent Toolkit.

**Start here: [`{toolkit}/CORE.md`]({toolkit}/CORE.md)**

That file routes you to the safety rules, the stack rules that apply to
what you are touching, the planning workflow, and the available skills.
It is deliberately short - read it fully.

Before any destructive or irreversible action (database, migration,
volume, deployment, server config) read [`{toolkit}/core/SAFETY.md`]({toolkit}/core/SAFETY.md) first.

{extra}"""


def _extra_for(agent: Agent, ctx: RenderContext) -> str:
    if agent.supports_skills and ctx.skills_mount:
        return (
            f"Project skills are available at `{ctx.skills_mount}` "
            f"(a link to `{TOOLKIT_DIR}/skills/`). Use them when relevant."
        )
    if ctx.skills:
        return (
            f"This tool has no skill loader. The equivalent guidance lives in "
            f"`{TOOLKIT_DIR}/skills/<name>/SKILL.md` - read the relevant one directly."
        )
    return ""


def instructions_for(agent: Agent, ctx: RenderContext) -> str:
    """Render the instruction file body for one agent."""
    style = agent.instructions.get("style")
    body = _POINTER_BODY.format(toolkit=TOOLKIT_DIR, extra=_extra_for(agent, ctx)).rstrip()

    if style == "dir-rules-mdc":
        # Cursor MDC: YAML frontmatter, always applied.
        return (
            "---\n"
            "description: Universal Agent Toolkit - project control plane and safety rules\n"
            "alwaysApply: true\n"
            "---\n\n"
            f"{body}\n"
        )

    if style == "dir-rules-md":
        return f"{body}\n"

    return f"{body}\n"


def agents_md(ctx: RenderContext) -> str:
    """The shared cross-agent instruction file."""
    body = _POINTER_BODY.format(
        toolkit=TOOLKIT_DIR,
        extra=(
            f"Skill-equivalent guidance lives in `{TOOLKIT_DIR}/skills/<name>/SKILL.md`. "
            "Read the relevant one directly if your tool has no skill loader."
            if ctx.skills
            else ""
        ),
    ).rstrip()
    return f"{body}\n"


def preserve_user_tail(existing: str, new_generated: str) -> str:
    """Keep anything the human wrote after the generated marker."""
    if GENERATED_MARK not in existing:
        return new_generated
    tail = existing.split(GENERATED_MARK, 1)[1]
    if not tail.strip():
        return new_generated
    return new_generated.rstrip("\n") + "\n" + tail


# ----------------------------------------------------------------------
# Workflow entry points
# ----------------------------------------------------------------------
#
# The workflow is only useful if it is easy to trigger. Claude Code gets real
# slash commands; every other agent gets the same instruction as a prompt it
# can be given directly (see START-HERE.md).

_PLAN_COMMAND = """---
description: Run the project workflow (triage -> plan -> gate -> build -> acceptance)
argument-hint: [what you want to build]
---

Run the project planning workflow defined in `{toolkit}/workflow/README.md`.

The request: $ARGUMENTS

Follow it exactly, in order:

1. **Read `{toolkit}/workflow/README.md` first.** Do not work from memory of
   what a planning process usually looks like.
2. **Triage** (`workflow/00-triage.md`). Classify the work as task, feature or
   product. Say the classification and which phases you will run and skip, and
   why, before going further.
3. **Check what already exists.** Read `{toolkit}/reports/` - if phases were
   already completed, resume rather than redo them.
4. **Run each phase in order**, using its own file in `{toolkit}/workflow/`.
   Each phase writes its report to `{toolkit}/reports/NN-phase.md` using
   `workflow/templates/report.md`.
5. **Respect the interaction mode** in `{toolkit}/project.json` (currently
   `{mode}`). It controls how much you ask, never whether safety gates apply.
6. **When the stack is decided (phase 06), install its rules (phase 07)**:
   `{uat} detect --project .` then `{uat} install --project . --agent {agent} --add <pack>`.
   Do not hand-write rules a pack already provides.
7. **Stop at the gate** (`workflow/11-gate.md`). Present the plan and wait for
   explicit approval. Do not begin implementing in the same message.
8. **After implementing, run acceptance** (`workflow/13-acceptance.md`). A
   green test suite is not the finish line: perform every journey from
   `docs/screens.md` against a running system and report anything you did not
   exercise as NOT VERIFIED.

## Skills belong to phases, not to this command

Do not invoke skills up front. Each phase names the skill it uses:

- phase 02 and 06 -> `brainstorming` (technique only)
- phase 10 -> `writing-plans` (it owns the plan format and location)
- phase 12 -> `subagent-driven-development` or `executing-plans`
- phase 13 -> the Playwright MCP, to drive journeys rather than screenshot them
- throughout implementation -> `test-driven-development`,
  `systematic-debugging`, `verification-before-completion`

**Read the "Precedence" section of `{toolkit}/workflow/README.md` before your
first skill.** Four skill instructions are superseded inside this workflow:
classify once in triage rather than re-classifying, batch questions instead of
one per message, one approval gate rather than two, and the skill's terminal
state does not apply because phases 03-09 sit before the plan.

Batch your questions. Never ask what the repository already answers.
"""

_PLAN_STATUS_COMMAND = """---
description: Show planning workflow progress for this project
---

Report the state of the project planning workflow.

1. Run `{uat} workflow --project .` and show the output.
2. Read every report in `{toolkit}/reports/` and summarise, in a few lines
   each: what was decided, what assumptions are outstanding, and what
   questions are still open.
3. State clearly which phase comes next and what it needs from the human.

Do not start the next phase. This command only reports.
"""

_RESUME_COMMAND = """---
description: Resume the planning workflow where it stopped
---

Resume the project planning workflow.

1. Read `{toolkit}/workflow/README.md` and `{toolkit}/project.json`.
2. Read every existing report in `{toolkit}/reports/` - these are decisions
   already made. Do not re-litigate them; if one looks wrong, say so and ask.
3. Identify the first phase with no report, and continue from there.
4. Follow that phase's file exactly and write its report on completion.

If all phases through 10 have reports, run the gate (`workflow/11-gate.md`)
and stop for approval.
"""

START_HERE = """# Start here

This project is configured by the Universal Agent Toolkit.

## To plan a project, a feature, or work on an unfamiliar codebase

Give your agent this instruction:

> Read `{toolkit}/workflow/README.md` and run the planning workflow.
> Start with triage, tell me the classification and which phases apply,
> then work through them in order. Stop at the gate for my approval.

{claude_note}
## To check progress

```bash
{uat} workflow --project .
```

Reports for completed phases are in `{toolkit}/reports/`. Read those before
resuming - they are the project's decision log.

## The sequence

| # | Phase | Produces |
|---|---|---|
| 00 | triage | class + phase list |
| 01 | discovery | reports/01-discovery.md |
| 02 | business logic | docs/business-logic.md |
| 03 | screens & flows | docs/screens.md |
| 04 | content | docs/content/ |
| 05 | design | docs/design/ |
| 06 | stack | docs/stack.md |
| 07 | rules | installed rule packs |
| 08 | architecture | docs/architecture.md |
| 09 | environments | Docker + deploy scripts |
| 10 | implementation plan | docs/plan.md |
| 11 | **gate** | go / no-go - approval never skipped |
| 12 | execute | working code |
| 13 | **acceptance** | every journey performed against a running system |

Triage decides how many of these apply. A one-line fix runs 01 and stops; a
new product runs everything.

## Installing rules for a new technology

```bash
{uat} detect  --project .
{uat} catalog
{uat} install --project . --agent {agent} --add <pack>
```

{uat_note}
"""

_CLAUDE_NOTE = """Claude Code has slash commands for this:

```
/plan <what you want to build>    start or continue the workflow
/plan-status                      show progress without advancing
/plan-resume                      pick up where it stopped
```

"""


def claude_commands(ctx: RenderContext) -> dict[str, str]:
    """Slash command files for Claude Code, keyed by filename."""
    agent = ctx.agents[0] if ctx.agents else "claude-code"
    fmt = dict(toolkit=TOOLKIT_DIR, uat=ctx.uat_cmd, agent=agent, mode=ctx.mode)
    return {
        "plan.md": _PLAN_COMMAND.format(**fmt),
        "plan-status.md": _PLAN_STATUS_COMMAND.format(**fmt),
        "plan-resume.md": _RESUME_COMMAND.format(**fmt),
    }


_EXTERNAL_NOTE = """`uat` lives in the Universal Agent Toolkit checkout, not in this project.
Either put its `bin/` on your PATH, or call it by path:

```bash
/path/to/universal-agent-toolkit/bin/uat status --project .
```

To remove that dependency entirely, embed the toolkit into this project:

```bash
/path/to/universal-agent-toolkit/bin/uat embed --project . --with-vendor
```

After that, use `./.agent-toolkit/toolkit/uat` and nothing external is needed.
"""

_EMBEDDED_NOTE = """The toolkit is embedded in this project at
`.agent-toolkit/toolkit/`, so these commands need nothing installed elsewhere.
"""


def start_here(ctx: RenderContext, *, claude: bool) -> str:
    embedded = ctx.uat_cmd.startswith(f"./{TOOLKIT_DIR}")
    return START_HERE.format(
        toolkit=TOOLKIT_DIR,
        uat=ctx.uat_cmd,
        agent=ctx.agents[0] if ctx.agents else "claude-code",
        claude_note=_CLAUDE_NOTE if claude else "",
        uat_note=_EMBEDDED_NOTE if embedded else _EXTERNAL_NOTE,
    )
